### ISSUE TITLE
"help" / "list" feature to see all devcmd tasks

### ISSUE THREAD

**Issue by lenaxus** [XITASO/devcmd#30]
There currently exists no "help" / "list" feature to see all devcmd tasks. To see all tasks, you have to navigate to the dev_cms folde.

The following approach would be desirable: 

- Type an command like this: `yarn devcmd help`
- Get an helpful output with the task names and maybe a short description. This can look for example like this: 
![image](https://user-images.githubusercontent.com/29269472/128035162-2bd519d3-8aad-4ee4-9672-94cea573d8d6.png)

**Comment by PatrickLehnerXI** [comment]
I think it would be better to use an "option" switch to `devcmd`, e.g. `--list`, instead of using a "task-like" plain command like `list`/`help`. Using an option switch is less likely to collide with an actual task (== script in the `dev_cmds` dir), since a project might want to define its own "list" or "help" command.
