### ISSUE TITLE
Yarn 3 script output not showing

### ISSUE THREAD

**Issue by ChrisDoernen** [XITASO/devcmd#37]
Hi Xitasonians,

Nice to see that devcmd is used more and more!

Don't know if it is actually an issue with devcmd. I noticed after upgrading yarn that the output from the scripts is not shown in the console anymore. Running the example command from the README, the only output I get is:

❯ yarn devcmd build
devcmd v0.0.8: cmd "build"

Did someone came across this yet? I hope I did not miss something super obvious...

Best
Chris

Versions:

❯ yarn --version
3.1.0
❯ node --version
v14.17.6
❯ npm --version
6.14.15

**Comment by PatrickLehnerXI** [comment]
@ChrisDoernen, thanks for pointing this out!

I have never tested DevCmd with Yarn 2+, so I'm not sure if it's an issue on our side or if it's a setup issue. I'll try to investigate some time soon.

(Yarn 2+ compatibility wasn't a priority so far because AFAIK we don't use it at XITASO at the moment, but we should also not exclude Yarn 2+ users if we can support it with reasonable effort)

**Comment by ChrisDoernen** [comment]
Hi Patrick, thanks for your response.

Today it miraculously started working as expected, so most probably the issue is more related to my setup than devcmd (although I did not change anything or at least am not aware). 

I'll post updates if I find the cause.

**Comment by PatrickLehnerXI** [comment]
Thanks for your update @ChrisDoernen, and sorry for my delayed response.

I'm glad DevCmd now works for you 🥳 
I'll close this issue for now, but I'm happy to hear any updates you may have. Feel free to add to this issue or open a new one if anything new comes up.
