### ISSUE TITLE
Bug in 0.0.10: ts-node is not found although available (yarn workspaces?)

### ISSUE THREAD

**Issue by Brunni** [XITASO/devcmd#55]
Hi!

I wanted to upgrade vom 0.0.8 to 0.0.10 but I now get this error:
`No script runner for TypeScript devcmds found. Did you forget to install ts-node?`

We are using yarn workspaces. ts-node is available in the node_modules folder on workspace level.

If I execute `npm ls ts-node` (which the `checkPackageAvailable` does) I get
```
PS E:\Projects\folder> npm ls ts-node
pos@ E:\Projects\folder
`-- ts-node@10.4.0  extraneous

npm ERR! extraneous: ts-node@10.4.0 E:\Projects\folder\node_modules\ts-node
PS E:\Projects\folder> 
```

**Comment by PatrickLehnerXI** [comment]
Hi @Brunni, thanks for reporting this!

Judging from your `npm ls` output and the [documentation for `npm ls`](https://docs.npmjs.com/cli/v7/commands/npm-ls), I'm assuming that `npm ls` returns a non-zero exit code because your ts-node is extraneous. DevCmd currently interprets any non-zero exit code of `npm ls ts-node` as "not available".

According to the [documentation of `npm prune`](https://docs.npmjs.com/cli/v7/commands/npm-prune):

> Extraneous packages are those present in the node_modules folder that are not listed as any package's dependency list.

So the fix for you is probably to add ts-node to your dependencies list and running `yarn install` again.

Please report back if this resolves your issue.

**Comment by Brunni** [comment]
Ok. It is now working correclty.

Nevertheless, I'm not sure, if the `npm ls` call is a good idea:
- It delays startup by about 5 Seconds in my project.
- It seems to be picky as seen in this thread.

**Comment by PatrickLehnerXI** [comment]
Good point, we definitely don't want flaky behavior for this. It was supposed to help users diagnose problems with TS command execution, but if it points in the wrong direction that's not at all helpful.

I'll create a new issue to investigate this.
